apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    # Source 1: kube-prometheus-stack Helm chart (من repo خارجي)
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 58.0.0
      helm:
        valueFiles:
          - $values/Kubernetes-Manifests-file/monitoring/helm/values.yaml

    # Source 2: نفس git repo متاعك - مرجع فقط لـ values.yaml
    - repoURL: https://github.com/HoussemDhahri/MERN-Stack-Devsecops-End-to-End-Project.git
      targetRevision: main
      ref: values

    # Source 3: kustomize resources (secrets, rules, servicemonitors, dashboards)
    - repoURL: https://github.com/HoussemDhahri/MERN-Stack-Devsecops-End-to-End-Project.git
      targetRevision: main
      path: Kubernetes-Manifests-file/monitoring

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=false