apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: todolist-database
spec:
  namespaceSelector:
    matchNames:
      - todolist-staging
  selector:
    matchLabels:
      app: todolist
      component: database
  endpoints:
    - port: mongodb
      path: /metrics
      interval: 30s