apiVersion: v1
kind: Secret
metadata:
  name: mongodb-uri-secret
  namespace: todolist
type: Opaque
stringData:
  MONGO_CONN_STR: mongodb://admin:houssemdhahri@todolist-database:27017/todolistdb?authSource=admin