apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rules/backend.yaml
  - rules/database.yaml
  - rules/infra.yaml
  - servicemonitors/backend-sm.yaml
  - servicemonitors/database-sm.yaml

commonLabels:
  release: monitoring