apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/frontend
  - ../../base/backend
  - ../../base/database

namespace: todolist-staging

replicas:
  - name: todolist-frontend
    count: 1
  - name: todolist-backend
    count: 1
  - name: todolist-database
    count: 1

images:
  - name: houssemdhahri93/todolist-frontend
    newTag: v1.0.0

  - name: houssemdhahri93/todolist-backend
    newTag: v1.0.0