apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolist-frontend
  labels:
    app: todolist
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todolist
      component: frontend
  template:
    metadata:
      labels:
        app: todolist
        component: frontend
    spec:
      containers:
        - name: frontend
          image: houssemdhahri93/todolist-frontend
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: todolist-frontend-config
                  key: REACT_APP_BACKEND_URL
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"