apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - telegram-bot-secret.yaml

secretGenerator:
  - name: alertmanager-custom-config
    files:
      - alertmanager.yaml=files/alertmanager.yaml
      - telegram.tmpl=files/telegram.tmpl
    options:
      disableNameSuffixHash: true